[information]
 name = "minai"
 background = "dark"
 author = "arrow2nd"

[palette]
  bg = "#232934"
  bg_light = "#384153"
  bg_dark = "#1B1F27"
  fg = "#E8E2D6"

  arm_band = "#92214A"
  frill = "#262626"
  frill_shadow = "#090B0A"
  foundation = "#DFC2BA"
  hair = "#818181"

  white = "#E8E2D6"
  gray = "#B3B8C2"
  blue = "#578CAD"
  green = "#BBCACB"
  cyan = "#76BFBA"
  red = "#C66471"
  orange = "#D4AF8D"
  yellow = "#BEBF70"
  purple = "#837591"
  magenta = "#B06E82"

[highlights]
  ColorColumn = "- bg"
  Conceal = "gray bg"
  Cursor = "fg bg"
  CursorIM = "link:Cursor"
  CursorColumn = "- bg"
  CursorLine = "- bg_light"
  CursorLineNr = "gray bg"
  Directory = "fg"
  DiffAdd = "green - ib"
  diffAdded = "link:DiffAdd"
  DiffChange = "yellow - ib"
  DiffDelete = "magenta - ib"
  diffRemoved = "link:DiffDelete"
  DiffText = "yellow - rb"
  ErrorMsg = "red"
  VertSplit = "hair bg"
  WinSeparator = "link:VertSplit"
  Folded = "gray bg_light"
  FoldColumn = "fg bg"
  SignColumn = "fg bg"
  IncSearch = "- - r"
  LineNr = "bg_light bg"
  LineNrAbove = "link:LineNr"
  LineNrBelow = "link:LineNr"
  MatchParen = "bg cyan"
  ModeMsg = "fg"
  MoreMsg = "fg"
  NonText = "hair"
  Normal = "fg bg"
  NormalFloat = "link:Normal"
  FloatBorder = "link:Normal"
  PMenu = "fg bg"
  PMenuSel = "fg bg_light b"
  PmenuSbar = "fg bg"
  PmenuThumb = "foundation foundation"
  Question = "fg"
  QuickFixLine = "- - r"
  Search = "bg magenta"
  CurSearch = "bg orange"
  SpecialKey = "hair"
  SpellBad = "red"
  SpellLocal = "fg"
  SpellCap = "fg"
  SpellRare = "fg"
  StatusLine = "gray frill_shadow"
  StatusLineNC = "link:StatusLine"
  TabLine = "gray bg i"
  TabLineFill = "link:TabLine"
  TabLineSel = "bg fg b"
  Title = "fg"
  Visual = "bg foundation"
  VisualNOS = "link:Visual"
  WarningMsg = "red"
  WildMenu = "- - r"

[syntax]
  Comment = "hair - i"
  Constant = "fg"
  String = "gray"
  Character = "link:Constant"
  Boolean = "foundation"
  Number = "foundation"
  Float = "foundation"
  Identifier = "foundation"
  Function = "fg"
  Statement = "green"
  Conditional = "link:Statement"
  Repeat = "link:Statement"
  Label = "link:Statement"
  Operator = "fg"
  Keyword = "link:Operator"
  Exception = "link:Operator"
  PreProc = "fg"
  Include = "link:PreProc"
  Define = "link:PreProc"
  Macro = "link:PreProc"
  PreCondit = "link:PreProc"
  Type = "fg"
  StorageClass = "link:Type"
  Structure = "link:Type"
  Typedef = "link:Type"
  Special = "link:Statement"
  SpecialChar = "link:Special"
  Tag = "link:Special"
  Delimiter = "link:Special"
  SpecialComment = "link:Special"
  Debug = "link:Special"
  Underlined = "gray - u"
  Ignore = "-"
  Error = "red"
  Todo = "green -"
  xmlAttrib = "link:Function"
  xmlAttribPunct = "link:Statement"
  xmlEndTag = "link:Statement"
  xmlNamespace = "link:Statement"
  xmlTag = "link:Statement"
  xmlTagName = "link:Statement"

  DiagnosticError = "link:Error"
  DiagnosticWarn = "yellow"
  DiagnosticInfo = "cyan"
  DiagnosticHint = "gray"
  DiagnosticOk = "green"
  LspInfoBorder = "link:Normal"
 
[treesitter]
  "@attribute" = "link:Special"
  "@boolean" = "link:Boolean"
  "@character" = "link:Constant"
  "@comment" = "link:Comment"
  "@comment.todo" = "link:Todo"
  "@comment.note" = "yellow"
  "@constructor" = "fg"
  "@conditional" = "link:Statement"
  "@constant" = "link:Constant"
  "@constant.builtin" = "link:Constant"
  "@constant.macro" = "link:Constant"
  "@error" = "link:Error"
  "@exception" = "link:Statement"
  "@function" = "link:Function"
  "@function.builtin" = "link:Function"
  "@function.macro" = "link:Function"
  "@function.method" = "link:@property"
  "@field" = "fg"
  "@float" = "link:number"
  "@number" = "link:number"
  "@number.float" = "link:Number"
  "@include" = "link:Statement"
  "@keyword" = "link:Statement"
  "@keyword.function" = "link:Statement"
  "@label" = "link:Special"
  "@namespace" = "link:Statement"
  "@mobule" = "link:Statement"
  "@operator" = "fg"
  "@parameter" = "fg"
  "@parameter.reference" = "fg"
  "@property" = "gray"
  "@punctuation.delimiter" = "fg"
  "@punctuation.bracket" = "fg"
  "@punctuation.special" = "link:Special"
  "@repeat" = "link:Statement"
  "@string" = "link:String"
  "@string.regex" = "link:String"
  "@string.regexp" = "link:String"
  "@string.special.url" = "link:Underlined"
  "@string.escape" = "link:Special"
  "@tag" = "link:Tag"
  "@tag.attribute" = "fg"
  "@tag.delimiter" = "link:Tag"
  "@text" = "gray"
  "@text.note" = "link:Todo"
  "@text.title" = "link:Title"
  "@text.uri" = "link:Underlined"
  "@markup" = "fg"
  "@markup.title" = "link:Title"
  "@markup.heading" = "link:Title"
  "@markup.list" = "link:Special"
  "@markup.link" = "link:Underlined"
  "@type" = "link:Type"
  "@type.builtin" = "link:Type"
  "@variable" = "fg"
  "@variable.builtin" = "link:Statement"
  "@variable.parameter" = "fg"
  "@variable.member" = "fg"

[mini]
  MiniStatuslineModeNormal = 'frill_shadow arm_band'
  MiniStatuslineModeInsert = "frill_shadow blue"
  MiniStatuslineModeVisual = "frill_shadow yellow"
  MiniStatuslineModeReplace = "frill_shadow orange"
  MiniStatuslineModeCommand = "frill_shadow purple"
  MiniStatuslineModeOther = "gray frill_shadow"
  MiniStatuslineDevinfo = "gray frill"
  MiniStatuslineFilename = "gray frill_shadow"
  MiniStatuslineFileinfo = "link:MiniStatuslineDevinfo"
  MiniStatuslineInactive = "link:StatusLineNC"
  MiniDiffSignAdd = "green - b"
  MiniDiffSignChange  = "yellow - b"
  MiniDiffSignDelete  = "magenta - b"
  MiniDiffOverAdd = "bg green"
  MiniDiffOverChange = "bg yellow"
  MiniDiffOverContext = "-"
  MiniDiffOverDelete  = "bg magenta"

[gitsign]
  GitSignsAdd = "green - b"
  GitSignsChange = "yellow - b"
  GitSignsDelete = "magenta - b"

[lazy]
  LazyButtonActive = "- arm_band b"
  LazyProgressTodo = "bg"

[neogit]
  NeogitHunkHeader = "blue"
  NeogitHunkHeaderHighlight = "link:NeogitHunkHeader"
  NeogitDiffContext = "- bg"
  NeogitDiffContextHighlight = "link:NeogitDiffContext"
  NeogitDiffAdd = "link:DiffAdd"
  NeogitDiffAddHighlight = "link:DiffAdd"
  NeogitDiffDelete = "link:DiffDelete"
  NeogitDiffDeleteHighlight = "link:DiffDelete"
  NeogitCommitViewHeader = "blue"
  NeogitDiffHeader = "blue"
  NeogitDiffHeaderHighlight = "link:NeogitDiffHeader"
  NeogitCursorLine = "link:CursorLine"
  NeogitPopupSwitchKey = "cyan"
  NeogitPopupOptionKey = "cyan"
  NeogitPopupConfigKey = "cyan"
  NeogitPopupActionKey = "cyan"
  NeogitBranch = "cyan"
  NeogitUntrackedfiles = "cyan"
  NeogitUnstagedchanges = "cyan"
  NeogitUnmergedchanges = "cyan"
  NeogitUnpulledchanges = "cyan"
  NeogitRecentcommits = "cyan"
  NeogitStagedchanges = "cyan"
  NeogitStashes = "cyan"
  NeogitRebasing = "cyan"

[pounce]
  PounceMatch = "fg"
  PounceGap = "fg"
  PounceAccept = "orange - bu"
  PounceAcceptBest = "magenta - bu"
  PounceUnmatched = "hair"

[ddu-converter-git_status]
  diffAdded = "link:DiffAdd"
  diffRemoved = "link:DiffDelete"

[render-markdown]
  RenderMarkdownH1Bg = "fg - b"
  RenderMarkdownH2Bg = "fg - b"
  RenderMarkdownH3Bg = "fg - b"
  RenderMarkdownH4Bg = "fg"
  RenderMarkdownH5Bg = "fg"
  RenderMarkdownH6Bg = "fg"
  RenderMarkdownCode = "- bg_dark"
  RenderMarkdownCodeInline = "- bg_dark"
